# C48

```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)
# library(hadron)
# library(kableExtra) # breaks latex
# library(tidyverse)

df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x, y)) +
    geom_point()
  assign("ggp", plotly::ggplotly(gg), envir = parent.frame())
  # ggp
  df # NOT returning a plot
}
res1 <- f1(df)
ggp # Let knit handle the plot
myplotly(ggplot())
# widgetframe::frameableWidget(ggplotly(ggp)%>%config(mathjax = "cdn") )
```


```{r, echo=FALSE,results='asis'}
dir <- "/home/garofalo/analysis/flow/data/out/"
file <- "onlinemeas_C48.dat_reweight_charm_OS_C48.dat_output"
mt <- read_df(paste0(dir, file))
all_obs <- Rose::get_all_corr(mt)
df<-NULL
df<-add_corr_to_df("M_{PS}",all_obs ,mt, df)
df<-add_corr_to_df("f_{PS}",all_obs ,mt, df)

df<-add_corr_to_df("plateau_dM/drewcOS",all_obs ,mt, df)
df<-add_corr_to_df("plateau_df/drewcOS",all_obs ,mt,df )



#######
file <- "onlinemeas_C48.dat_reweight_strange_OS_C48.dat_output"
mt <- read_df(paste0(dir, file))
all_obs <- Rose::get_all_corr(mt)
# df<-NULL
df<-add_corr_to_df("plateau_dM/drewsOS",all_obs ,mt, df)
df<-add_corr_to_df("plateau_df/drewsOS",all_obs ,mt,df )
#######
file <- "onlinemeas_C48.dat_reweight_light_OS_C48.dat_output"
mt <- read_df(paste0(dir, file))
all_obs <- Rose::get_all_corr(mt)
# df<-NULL
df<-add_corr_to_df("plateau_dM/drewlOS",all_obs ,mt, df)
df<-add_corr_to_df("plateau_df/drewlOS",all_obs ,mt,df )

####
gg<-plot_df_corr_ggplot(df)
fig<-myplotly(gg,"","t/a","",to_print = TRUE)

```


## Compare charm precision

```{r, echo=FALSE,results='asis'}
dir <- "/home/garofalo/analysis/flow/data/out/"
file <- "onlinemeas_C48.dat_reweight_charm_OS_C48.dat_output"
mt <- read_df(paste0(dir, file))
all_obs <- Rose::get_all_corr(mt)
df<-NULL
# df<-add_corr_to_df("M_{PS}",all_obs ,mt, df)
# df<-add_corr_to_df("f_{PS}",all_obs ,mt, df)

# df<-add_corr_to_df("plateau_dM/drewcOS",all_obs ,mt, df)
# df<-add_corr_to_df("plateau_df/drewcOS",all_obs ,mt,df )
df<-add_corr_to_df("plateau_dM/drewcOS",all_obs ,mt, df,rename="plateau_dM/drewcOS_1e-28")
df<-add_corr_to_df("plateau_df/drewcOS",all_obs ,mt,df,rename="plateau_df/drewcOS_1e-28" )


#######
file <- "onlinemeas_C48.dat_reweight_charm_OS_C48_low_prec.dat_output"
mt <- read_df(paste0(dir, file))
all_obs <- Rose::get_all_corr(mt)
# df<-NULL
df<-add_corr_to_df("plateau_dM/drewcOS",all_obs ,mt, df,rename="plateau_dM/drewcOS_1e-18")
df<-add_corr_to_df("plateau_df/drewcOS",all_obs ,mt,df,rename="plateau_df/drewcOS_1e-18" )


####
gg<-plot_df_corr_ggplot(df)
fig<-myplotly(gg,"","t/a","",to_print = TRUE)

```

## Check thermalization

label no[0-500]a means that we remove the configurations from 0 to 500 in replica a

```{r, echo=FALSE,results='asis'}
dir <- "/home/garofalo/analysis/flow/data/out/"
file <- "onlinemeas_C48.dat_reweight_charm_OS_C48.dat_output"
mt <- read_df(paste0(dir, file))
all_obs <- Rose::get_all_corr(mt)
df<-NULL
df<-add_corr_to_df("M_{PS}",all_obs ,mt, df)
df<-add_corr_to_df("f_{PS}",all_obs ,mt, df)

# df<-add_corr_to_df("plateau_dM/drewcOS",all_obs ,mt, df)
# df<-add_corr_to_df("plateau_df/drewcOS",all_obs ,mt,df )
df<-add_corr_to_df("plateau_dM/drewcOS",all_obs ,mt, df,rename="plateau_dM/drewcOS")
df<-add_corr_to_df("plateau_df/drewcOS",all_obs ,mt,df,rename="plateau_df/drewcOS" )


#######
file <- "onlinemeas_C48_therm.dat_reweight_charm_OS_C48_therm.dat_output"
mt <- read_df(paste0(dir, file))
all_obs <- Rose::get_all_corr(mt)

df<-add_corr_to_df("M_{PS}",all_obs ,mt, df, rename ="M_{PS}_no[0-500]a" )
df<-add_corr_to_df("f_{PS}",all_obs ,mt, df, rename ="f_{PS}_no[0-500]a")

df<-add_corr_to_df("plateau_dM/drewcOS",all_obs ,mt, df,rename="plateau_dM/drewcOS_no[0-500]a")
df<-add_corr_to_df("plateau_df/drewcOS",all_obs ,mt,df,rename="plateau_df/drewcOS_no[0-500]a" )


####
gg<-plot_df_corr_ggplot(df)
fig<-myplotly(gg,"","t/a","",to_print = TRUE)

```

## History

the vertical line is at the configuration 0001_r1 the order of the confs
is (_r0 backward) (_r1 forward)

```{r, echo=FALSE,results='asis'}
dfl<- read.table("/home/garofalo/analysis/flow/data/out/onlinemeas_C48.dat_reweight_light_OS_C48.dat_history.txt", header = TRUE)
dfs<- read.table("/home/garofalo/analysis/flow/data/out/onlinemeas_C48.dat_reweight_strange_OS_C48.dat_history.txt", header = TRUE)
dfc<- read.table("/home/garofalo/analysis/flow/data/out/onlinemeas_C48.dat_reweight_charm_OS_C48.dat_history.txt", header = TRUE)

gg<-ggplot()+theme_bw()
gg<- gg+ geom_line(aes(x=dfl$conf_id , y=dfl$r, color= "l"))
gg<- gg+ geom_line(aes(x=dfs$conf_id , y=dfs$r, color= "s"))
gg<- gg+ geom_line(aes(x=dfc$conf_id , y=dfc$r, color= "c"))
gg<- gg+ geom_vline(xintercept = dfc$conf_id[ dfc$conf_name == "0001_r1" ])
fig<-myplotly(gg,"","id","r", to_print = TRUE)
gg<-ggplot()+theme_bw()
gg<- gg+ geom_line(aes(x=dfl$conf_id , y=dfl$M_PS, color= "l"))
# gg<- gg+ geom_line(aes(x=dfs$conf_id , y=dfs$M_PS, color= "s"))
# gg<- gg+ geom_line(aes(x=dfc$conf_id , y=dfc$M_PS, color= "c"))
gg<- gg+ geom_vline(xintercept = dfc$conf_id[ dfc$conf_name == "0001_r1" ])
fig<-myplotly(gg,"","id","Mpi", to_print = TRUE)


```


## compare values with B32 and B24


```{r, echo=FALSE,results='asis'}
dir <- "/home/garofalo/analysis/flow/data/out/"
file <- "onlinemeas_C48.dat_reweight_charm_OS_C48.dat_output"
mt <- read_df(paste0(dir, file))
all_obs <- Rose::get_all_corr(mt)
df<-NULL
df<-add_corr_to_df("M_{PS}",all_obs ,mt, df,rename="M-C48")
df<-add_corr_to_df("f_{PS}",all_obs ,mt, df,rename="f-C48")

#gg<-plot_df_corr_ggplot(df)
# fig<-myplotly(gg,"","t/a","",to_print = TRUE)
#######
file <- "onlinemeas_B32.dat_reweight_strange_OS_B32.dat_output"
mt <- read_df(paste0(dir, file))
all_obs <- Rose::get_all_corr(mt)
df<-add_corr_to_df("M_{PS}",all_obs ,mt, df,rename="M-B32")
df<-add_corr_to_df("f_{PS}",all_obs ,mt, df,rename="f-B32")
#######
file <- "onlinemeas_B24.dat_reweight_strange_OS_B24.dat_output"
mt <- read_df(paste0(dir, file))
all_obs <- Rose::get_all_corr(mt)
df<-add_corr_to_df("M_{PS}",all_obs ,mt, df,rename="M-B24")
df<-add_corr_to_df("f_{PS}",all_obs ,mt, df,rename="f-B24")
a_C<-0.06819/197.37
a_B<-0.07948/197.37
# df <- df %>%
#   mutate(y = ifelse(grepl("C", label), y / a_C, y))
# df <- df %>%
#   mutate(y = ifelse(grepl("B", label), y / a_B, y))
df[grepl("C", df$label), c(2,3,5,6)]<- df[grepl("C", df$label),c(2,3,5,6)]/a_C
df[grepl("B", df$label), c(2,3,5,6)]<- df[grepl("B", df$label),c(2,3,5,6)]/a_B
####
gg<-plot_df_corr_ggplot(df)
fig<-myplotly(gg,"","t/a","",to_print = TRUE)

```
