## fpi A0P5



```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)


df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x, y)) +
    geom_point()
  assign("ggp", plotly::ggplotly(gg), envir = parent.frame())
  # ggp
  df # NOT returning a plot
}
res1 <- f1(df)
ggp # Let knit handle the plot
myplotly(ggplot())
```

## B64


```{r, results='asis', echo=FALSE}
df <- NULL
li<-c("l0")
for (l in li){
for (obs in c("M_{PS}", "M_{PS}_mu", "fpi_P5A0", "fpi_P5A0_mu", "f_{PS}", "f_{PS}_mu", "M_{PS}_A0")){
mt <- read_df(paste0("/home/garofalo/analysis/flow/data_fpi_A0//out/B64_tm_",l,"_",l,"_A0P5.dat_output"))
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df(obs, all_obs, mt, df, print_res = FALSE, reshape = T, rename=paste0(obs,"_",l))
}}
gg <- plot_df_corr_ggplot(df, width = 0.05)

fig <- myplotly(gg, "", "$t/a$", "$m_{eff}(t)$", to_print = TRUE)

```

### OS

```{r, results='asis', echo=FALSE}
df <- NULL
li<-c("l0")
for (l in li){
for (obs in c("M_{PS}", "M_{PS}_mu", "fpi_P5A0", "fpi_P5A0_mu",  "M_{PS}_A0")){
mt <- read_df(paste0("/home/garofalo/analysis/flow/data_fpi_A0//out/B64_OS_",l,"_",l,"_A0P5.dat_output"))
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df(obs, all_obs, mt, df, print_res = FALSE, reshape = T, rename=paste0(obs,"_",l))
}}
gg <- plot_df_corr_ggplot(df, width = 0.05)

fig <- myplotly(gg, "", "$t/a$", "$m_{eff}(t)$", to_print = TRUE)

```

## B24

```{r, results='asis', echo=FALSE}
df <- NULL
li<-c("l0","l1","l2")
for (l in li){
for (obs in c("M_{PS}", "M_{PS}_mu", "fpi_P5A0", "fpi_P5A0_mu", "f_{PS}")){
mt <- read_df(paste0("/home/garofalo/analysis/flow/data_fpi_A0//out/B24_tm_",l,"_",l,"_A0P5.dat_reweight_charm_OS_B24.dat_output"))
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df(obs, all_obs, mt, df, print_res = FALSE, reshape = T, rename=paste0(obs,"_",l))
}}
gg <- plot_df_corr_ggplot(df, width = 0.05)

fig <- myplotly(gg, "", "$t/a$", "$m_{eff}(t)$", to_print = TRUE)

```

```{r, results='asis', echo=FALSE}
df <- NULL
li<-c("l0","l1","l2")
for (l in li){
for (obs in c("pateau_deriv_fpi_P5A0")){
mt <- read_df(paste0("/home/garofalo/analysis/flow/data_fpi_A0//out/B24_tm_",l,"_",l,"_A0P5.dat_reweight_charm_OS_B24.dat_output"))
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df(obs, all_obs, mt, df, print_res = FALSE, reshape = T, rename=paste0(obs,"_",l))
}}
gg <- plot_df_corr_ggplot(df, width = 0.05)

fig <- myplotly(gg, "", "$t/a$", "$m_{eff}(t)$", to_print = TRUE)

```

```{r,results='asis',echo=FALSE, warning=FALSE}
gg <- NULL
basenames <- c(
  "/home/garofalo/analysis/flow/data_fpi_A0/fit_smallV_phys_point/fit_smallV_B24_fpi_A0P5_deriv_fpi_A0P5_xi_xi2",
  "/home/garofalo/analysis/flow/data_fpi_A0/fit_smallV_phys_point/fit_smallV_B24_OS_fpi_A0P5_deriv_fpi_A0P5_xi_xi2",
  "/home/garofalo/analysis/flow/data_fpi_A0/fit_smallV_phys_point/fit_smallV_B24_fpi_A0P5_deriv_fpi_WTI_xi_xi2"
)
labels <- c(
  "fpi_A0P5 ",
  "fpi_A0P5_OS ",
  "fpi_WTI "
)


for (j in seq_along(basenames)) {
  print(basenames[j])
  fit <- Rose::read_fit_P_file(paste0(basenames[j], "_fit_P.dat"))
  # print(make_table_fit_result(fit))
  gg <- plot_fit(basenames[j], "amu",
    # noline = TRUE,
    data_type = labels[j],
    gg = gg,
    id_x = 1,
    single_name_for_fit = labels[j],
    width = 0.0001,
    nudge = j * 0.00001
  )
}
# fpi_FLAG <- (135.0/130.5)^2

# gg <- gg + geom_vline(xintercept = fpi_FLAG, linetype = "dashed") #+annotate("text", x = 0.0002, y = fpi_FLAG-0.2, label="FLAG")
# gg <- gg + geom_point(aes(x = 0, y = fpi_FLAG, color = "FLAG", shape = "FLAG", fill = "FLAG"))

fig <- myplotly(gg, "", "$M_\\pi/f_\\pi$", "$\\mu_\\ell/ f_{\\pi}df_\\pi/d\\mu_c$",
  to_print = TRUE,
  # yrange = c(-1, 4), 
  legend_position = c(0.7, 0.98)
)
```

## B32

```{r, results='asis',echo=FALSE}
df <- NULL
li<-c("l0","l1","l2")
for (l in li){
for (obs in c("M_{PS}", "M_{PS}_mu", "fpi_P5A0", "fpi_P5A0_mu", "f_{PS}","pateau_deriv_fpi_P5A0")){
mt <- read_df(paste0("/home/garofalo/analysis/flow/data_fpi_A0//out/B32_tm_",l,"_",l,"_A0P5.dat_reweight_charm_OS_B32.dat_output"))
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df(obs, all_obs, mt, df, print_res = FALSE, reshape = T, rename=paste0(obs,"_",l))
}}
gg <- plot_df_corr_ggplot(df, width = 0.05)

fig <- myplotly(gg, "", "$t/a$", "$m_{eff}(t)$", to_print = TRUE)

```



```{r,results='asis',echo=FALSE, warning=FALSE}
gg <- NULL
basenames <- c(
  "/home/garofalo/analysis/flow/data_fpi_A0/fit_smallV_phys_point/fit_smallV_B32_fpi_A0P5_deriv_fpi_A0P5_xi_xi2",
  "/home/garofalo/analysis/flow/data_fpi_A0/fit_smallV_phys_point/fit_smallV_B32_OS_fpi_A0P5_deriv_fpi_A0P5_xi_xi2",
  "/home/garofalo/analysis/flow/data_fpi_A0/fit_smallV_phys_point/fit_smallV_B32_fpi_A0P5_deriv_fpi_WTI_xi_xi2"
)
labels <- c(
  "fpi_A0P5 ",
  "fpi_A0P5_OS ",
  "fpi_WTI "
)


for (j in seq_along(basenames)) {
  print(basenames[j])
  fit <- Rose::read_fit_P_file(paste0(basenames[j], "_fit_P.dat"))
  # print(make_table_fit_result(fit))
  gg <- plot_fit(basenames[j], "amu",
    # noline = TRUE,
    data_type = labels[j],
    gg = gg,
    id_x = 1,
    single_name_for_fit = labels[j],
    width = 0.0001,
    nudge = j * 0.00001
  )
}
# fpi_FLAG <- (135.0/130.5)^2

# gg <- gg + geom_vline(xintercept = fpi_FLAG, linetype = "dashed") #+annotate("text", x = 0.0002, y = fpi_FLAG-0.2, label="FLAG")
# gg <- gg + geom_point(aes(x = 0, y = fpi_FLAG, color = "FLAG", shape = "FLAG", fill = "FLAG"))

fig <- myplotly(gg, "", "$M_\\pi/f_\\pi$", "$\\mu_\\ell/ f_{\\pi}df_\\pi/d\\mu_c$",
  to_print = TRUE,
  # yrange = c(-1, 4), 
  legend_position = c(0.7, 0.98)
)
```

## averaging ens

```{r,results='asis',echo=FALSE, warning=FALSE}
gg <- NULL
basenames <- c(
  "/home/garofalo/analysis/flow/data_fpi_A0/fit_smallV_phys_point/average_mul_over_fpi_df_dmuc_smallV_OS_fpi_A0P5_deriv_fpi_A0P5_const"
)
labels <- c(
  "fpi_A0P5 "
)


for (j in seq_along(basenames)) {
  print(basenames[j])
  fit <- Rose::read_fit_P_file(paste0(basenames[j], "_fit_P.dat"))
  # print(make_table_fit_result(fit))
  gg <- plot_fit(basenames[j], "L",
    # noline = TRUE,
    # data_type = ,
    gg = gg,
    id_x = 1,
    single_name_for_fit = labels[j],
    width = 0.0001,
    nudge = j * 0.00001
  )
}

fig <- myplotly(gg, "", "$L$", "$\\mu_\\ell/ f_{\\pi}df_\\pi/d\\mu_c$",
  to_print = TRUE,
  # yrange = c(-1, 4), 
  legend_position = c(0.7, 0.98)
)
```