# statistical analysis reweighting


```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)


df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x, y)) +
    geom_point()
  assign("ggp", plotly::ggplotly(gg), envir = parent.frame())
  # ggp
  df # NOT returning a plot
}
res1 <- f1(df)
ggp # Let knit handle the plot
myplotly(ggplot())
```

to reweigh an observable we have to compute

$$
\frac{\int dU e^{-S[U]} O(U) r(U)}{\int dU e^{-S[U]}r(U)}= \frac{\int dU e^{-S[U]} O(U) r(U)}{\int dU e^{-S[U]}r(U)} \frac{\int dU e^{-S[U]}}{\int dU e^{-S[U]}} = 
\frac{\langle Or \rangle}{\langle r\rangle}\,.
$$
$r$ is computed stochastically as 
$$
r(U)= \langle r(U) \rangle_\phi= \det\left(D(\mu_f)/D(\mu_i)\right) = \int d\phi e^{w(U,\phi)}
$$
with $w(U,\phi)=\phi^\dagger(1-D(\mu_i) D^{-1}(\mu_f))\phi$ and $\phi$ a gaussian noise $P(\phi)\propto e^{-\phi^2}$.

Since $\det\left(D(\mu_f)/D(\mu_i)\right)$ may be complex we compute
$$
\left| \det\left(D(\mu_f)/D(\mu_i)\right)\right|=\sqrt{\det\left(D^{-1}(\mu_i)D(\mu_f)D(-\mu_f)D^{-1}(-\mu_i)\right)}\\
=\left(\int d\phi e^{\phi^\dagger(1-D(-\mu_i)D^{-1}(-\mu_f)D^{-1}(\mu_f)D(\mu_i))\phi}\right)^{\frac{1}{2}}
$$ 
, thus the observable to compute is 

$$
\frac{\langle O \langle r\rangle_\phi \rangle_U}{\langle \langle r\rangle_\phi\rangle_{U}}\,.
$$
we can not compute $r(U_i,\phi_{ij})$ with double precision, but we can compute
the exponent of its sum over $\phi$ as $e^{w(U_i)}=\langle r(U_i,\phi)\rangle_\phi=\frac{1}{N_\phi}\sum_\phi r(U_i,\phi)+O\left(\frac{1}{N_\phi}\right)$
   $$
w(U_i)=\log \left(\frac{1}{N_j}\sum_j r(U_i,\phi_{ij})\right)= w(U_i,\phi_{i0})+\log\left(\frac{1}{N_j}\sum_j e^{w(U_i,\phi_{ij})- w(U_i,\phi_{i0})}\right)\,.\\
   $$ {#eq-wu}
   For the case of an OS reweighting we need to take into account the square root factor 
   $e^{w(U_i)}=\left(\langle r(U_i,\phi)\rangle_\phi\right)^{1/2}$ as
   $$
w(U_i)=\frac{1}{2}\log \left(\frac{1}{N_j}\sum_j r(U_i,\phi_{ij})\right)= \frac{1}{2}w(U_i,\phi_{i0})+\frac{1}{2}\log\left(\frac{1}{N_j}\sum_j e^{w(U_i,\phi_{ij})- w(U_i,\phi_{i0})}\right)\,.\\
   $$ {#eq-wu-OS}
   
then we can multiply numerator and denominator by a factor to make the computation
doable in double precision
$$
\frac{\langle O \langle r\rangle_\phi \rangle_U e^{-\bar w}}{\langle \langle r\rangle_\phi\rangle_{U}e^{-\bar w}}\,.
$$
with $\bar w = \sum_U w(U)$. At this stage $\langle \langle r\rangle_\phi\rangle_{U}e^{-\bar w}$
can be computed as
$$
\langle \langle r\rangle_\phi\rangle_{U}e^{-\bar w} =\frac{1}{N_U} \sum_U e^{w(U)-\bar w}
$$
