# Pion B64

```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)


df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x, y)) +
    geom_point()
  assign("ggp", plotly::ggplotly(gg), envir = parent.frame())
  # ggp
  df # NOT returning a plot
}
res1 <- f1(df)
ggp # Let knit handle the plot
myplotly(ggplot())
masses <- c(
  0.0006669,
  0.018267,
  0.23134
)
```

## Pion only sea corrections

```{r, results='asis',echo=FALSE}
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- NULL
df <- add_corr_to_df("M_{PS}", all_obs, mt, df, print_res = FALSE, reshape = T)
df <- add_corr_to_df("M_{PS}+mul_correction", all_obs, mt, df, print_res = FALSE, reshape = T, nudge = 0.1)
df <- add_corr_to_df("M_{PS}+mus_correction", all_obs, mt, df, print_res = FALSE, reshape = T, nudge = 0.2)
df <- add_corr_to_df("M_{PS}+muc_correction", all_obs, mt, df, print_res = FALSE, reshape = T, nudge = 0.3)
# df <- add_corr_to_df("W+all_mu_correction(t)", all_obs, mt, df, print_res = FALSE, reshape = FALSE)

print_full_res("M_{PS}", all_obs, mt)
print_full_res("M_{PS}+mul_correction", all_obs, mt)
print_full_res("M_{PS}+mus_correction", all_obs, mt)
print_full_res("M_{PS}+muc_correction", all_obs, mt)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewlTM", all_obs, mt, df, print_res = FALSE, nudge = 0.6, reshape = T)
# print_full_res("w0_rewlTM", all_obs, mt)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_strange_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewsOS", all_obs, mt, df, print_res = FALSE, nudge = 0.5, reshape = T)
# print_full_res("w0_rewsOS", all_obs, mt)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewcOS", all_obs, mt, df, print_res = FALSE, nudge = 0.4, reshape = T)
# print_full_res("w0_rewcOS", all_obs, mt)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_sc_ndg_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rew_scndgTM", all_obs, mt, df, print_res = FALSE, nudge = 0.4, reshape = T)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.25_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewcOS_0.25", all_obs, mt, df, print_res = FALSE, nudge = 0.4, reshape = T)
######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.02_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewcOS_0.02", all_obs, mt, df, print_res = FALSE, nudge = 0.4, reshape = T)
######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_ndg_charm0.1_strange0_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rew_charm0.1_strange0_ndgTM", all_obs, mt, df, print_res = FALSE, nudge = 0.4, reshape = T)


### plot
gg <- plot_df_corr_ggplot(df, width = 0.05)

fig <- myplotly(gg, "", "$t/a$", "$m_{eff}(t)$", to_print = TRUE)
```

```{r, results='asis',echo=FALSE}

mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- NULL
df <- add_corr_to_df("Delta_mul_M_{PS}", all_obs, mt, df, print_res = TRUE, reshape = T)
df <- add_corr_to_df("Delta_mus_M_{PS}", all_obs, mt, df, print_res = TRUE, reshape = T, nudge = 0.1)
df <- add_corr_to_df("Delta_muc_M_{PS}", all_obs, mt, df, print_res = TRUE, reshape = T, nudge = 0.2)

### plot
gg <- plot_df_corr_ggplot(df, width = 0.05)

fig <- myplotly(gg, "", "$t/a$", "$dm_{eff}(t)/d\\mu$", to_print = TRUE)
```

## $f_\pi$

```{r, results='asis',echo=FALSE}
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- NULL
df <- add_corr_to_df("f_{PS}", all_obs, mt, df, print_res = T, reshape = T)
df <- add_corr_to_df("f_{PS}+mul_correction", all_obs, mt, df, print_res = T, reshape = T, nudge = 0.1)
df <- add_corr_to_df("f_{PS}+mus_correction", all_obs, mt, df, print_res = T, reshape = T, nudge = 0.2)
df <- add_corr_to_df("f_{PS}+muc_correction", all_obs, mt, df, print_res = T, reshape = T, nudge = 0.3)
print_full_res("df_{PS}/dmuc_correction",all_obs ,mt)
# print_full_res("f_{PS}(iso)_muc_correction",all_obs ,mt)
print_full_res("f_{PS}+muc_correction",all_obs ,mt)

# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
# df <- add_corr_to_df("f_{PS}", all_obs, mt, df, print_res = FALSE, nudge = 0.6, reshape = T)
df <- add_corr_to_df("f_{PS}_rewlTM", all_obs, mt, df, print_res = T, nudge = 0.6, reshape = T)
# print_full_res("w0_rewlTM", all_obs, mt)
print_full_res("df_{PS}/drewlTM",all_obs ,mt)
# print_full_res("f_{PS}(mciso)_rewlTM",all_obs ,mt)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_strange_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("f_{PS}_rewsOS", all_obs, mt, df, print_res = T, nudge = 0.5, reshape = T)
# print_full_res("w0_rewsOS", all_obs, mt)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("f_{PS}_rewcOS", all_obs, mt, df, print_res = T, nudge = 0.4, reshape = T)
# print_full_res("w0_rewcOS", all_obs, mt)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_sc_ndg_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("f_{PS}_rew_scndgTM", all_obs, mt, df, print_res = T, nudge = 0.4, reshape = T)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.25_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("f_{PS}_rewcOS_0.25", all_obs, mt, df, print_res = T, nudge = 0.4, reshape = T)

print_full_res("df_{PS}/drewcOS_0.25",all_obs ,mt)
print_full_res("f_{PS}(mciso)_rewcOS_0.25",all_obs ,mt)

######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.02_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("f_{PS}_rewcOS_0.02", all_obs, mt, df, print_res = T, nudge = 0.4, reshape = T)
###
print_full_res("df_{PS}/drewcOS_0.02",all_obs ,mt)
print_full_res("f_{PS}(mciso)_rewcOS_0.02",all_obs ,mt)

######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.1_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
#df <- add_corr_to_df("f_{PS}_rewcOS_0.1", all_obs, mt, df, print_res = T, nudge = 0.4, reshape = T)
print_full_res("df_{PS}/drewcOS_0.1",all_obs ,mt)
print_full_res("f_{PS}(mciso)_rewcOS_0.1",all_obs ,mt)
######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_charm_0.1_OS_B64_LMA.dat_output")
all_obs <- Rose::get_all_corr(mt)
print("same statistic of gm2 LMA")
#df <- add_corr_to_df("f_{PS}_rewcOS_0.1", all_obs, mt, df, print_res = T, nudge = 0.4, reshape = T)
print_full_res("df_{PS}/drewcOS_0.1",all_obs ,mt)
print_full_res("f_{PS}(mciso)_rewcOS_0.1",all_obs ,mt)
print("---")
######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_ndg_charm0.1_strange0_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
print_full_res("df_{PS}/drew_charm0.1_strange0_ndgTM",all_obs ,mt)
print_full_res("f_{PS}(mciso)_rew_charm0.1_strange0_ndgTM",all_obs ,mt)



df$y<- df$y*sqrt(2)*0.1394265
df$fit<- df$fit*sqrt(2)*0.1394265
gg <- plot_df_corr_ggplot(df, width = 0.05)

fig <- myplotly(gg, "", "$t/a$", "$af_{PS}(t)$", to_print = TRUE)
```

## Analytic derivative

```{r, results='asis',echo=FALSE}
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- NULL
df <- add_corr_to_df("Delta_mul_f_{PS}", all_obs, mt, df, print_res = T, reshape = T)


df$y<- df$y
df$fit<- df$fit
gg <- plot_df_corr_ggplot(df, width = 0.05)

fig <- myplotly(gg, "", "$t/a$", "$af_{PS}(t)$", to_print = TRUE)
```

## derivative

```{r, results='asis',echo=FALSE}
df <- data.frame(
  "dm" = c(0),
  "ddm" = c(0),
  "label" = c("")
)
df <- df[-1, ]
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "dM_{PS}/drewlTM"
res <- get_full_res(name, all_obs, mt) / 2
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0("   ", name))
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_strange_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "dM_{PS}/drewsOS"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0("  ", name))

# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.25_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "dM_{PS}/drewcOS_0.25"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0(" ", name))
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.02_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "dM_{PS}/drewcOS_0.02"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0(" ", name))
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_ndg_charm0.1_strange0_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "dM_{PS}/drew_charm0.1_strange0_ndgTM"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0(" ", name))

# ######################## loops
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "dM_{PS}/dmul_correction"
res <- get_full_res(name, all_obs, mt) / 2
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0("     ", name))
name <- "dM_{PS}/dmus_correction"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0("     ", name))
name <- "dM_{PS}/dmuc_correction"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0("    ", name))


## plot
gg <- myggplot(fill = FALSE)
gg <- gg + geom_pointrange(
  data = df,
  aes(x = label, y = dm, ymin = dm - ddm, ymax = dm + ddm, color = label, shape = label)
)
gg <- gg + theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))
gg<- gg + theme(legend.position = "none")

fig <- myplotly(gg, "", "", "$dM/d\\mu$", to_print = TRUE, legend_position =  NULL)
```

```{r, results='asis',echo=FALSE}
df <- data.frame(
  "dm" = c(0),
  "ddm" = c(0),
  "label" = c(""),
  "mass" = c(0),
  "name" = c("")
)
df <- df[-1, ]
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/drewlTM"
res <- get_full_res(name, all_obs, mt) / 2
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", masses[1], name)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_strange_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/drewsOS"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", masses[2], name)

# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.25_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/drewcOS_0.25"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", masses[3], name)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.02_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/drewcOS_0.02"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", masses[3], name)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.1_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/drewcOS_0.1"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", masses[3], name)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_charm_0.1_OS_B64_LMA.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/drewcOS_0.1"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", masses[3], paste0(name,"_LMA"))

# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_step_0.03125_to_0.03152408_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/drew_0.03125_to_0.03152408_OS"
res <- get_full_res(name, all_obs, mt)
mass <- get_full_res("mu_in", all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", mass[1,1], name)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_step_0.01_to_0.01027408_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/drew_0.01_to_0.01027408_OS"
res <- get_full_res(name, all_obs, mt)
mass <- get_full_res("mu_in", all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", mass[1,1], name)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_step_0.1232229005_to_0.1234969805_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/drew_0.1232229005_to_0.1234969805_OS"
res <- get_full_res(name, all_obs, mt)
mass <- get_full_res("mu_in", all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", mass[1,1], name)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_ndg_charm0.1_strange0_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/drew_charm0.1_strange0_ndgTM"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", mass[1,1], name)


# # ######################## loops
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "df_{PS}/dmul_correction"
res <- get_full_res(name, all_obs, mt) / 2
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "loop", masses[1], name)
name <- "df_{PS}/dmus_correction"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "loop", masses[2], name)
name <- "df_{PS}/dmuc_correction"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "loop", masses[3], name)


## plot
gg <- ggplot() +
  theme_bw() # myggplot(fill = FALSE)
gg <- gg + geom_pointrange(
  data = df,
  aes(x = 1 / mass+5*runif(length(mass)), y = dm, ymin = dm - ddm, ymax = dm + ddm, color = name, shape = label)
)
gg <- gg + theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))

fig <- myplotly(gg, "", "$1/am$", "$df_{PS}/d\\mu$",
  to_print = TRUE,
  legend_position = c(0,0)
)
###
gg <- ggplot() +
  theme_bw() # myggplot(fill = FALSE)
gg <- gg + geom_pointrange(
  data = df,
  aes(x =  mass +0.002*runif(length(mass)) , y = dm, ymin = dm - ddm, ymax = dm + ddm, color = name, shape = label)
)
gg <- gg + theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))

fig <- myplotly(gg, "", "$am$", "$df_{PS}/d\\mu$",
  to_print = TRUE,
  legend_position = c(0.5,0)
  )
```

```{r, results='asis',echo=FALSE}
df <- data.frame(
  "dm" = c(0),
  "ddm" = c(0),
  "label" = c(""),
  "mass" = c(0),
  "name" = c("")
)
df <- df[-1, ]
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "f_{PS}d(M_{PS}/f_{PS})/drewlTM"
res <- get_full_res(name, all_obs, mt) / 2
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", masses[1], name)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_strange_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "f_{PS}d(M_{PS}/f_{PS})/drewsOS"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", masses[2], name)

# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.25_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "f_{PS}d(M_{PS}/f_{PS})/drewcOS_0.25"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", masses[3], name)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.02_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "f_{PS}d(M_{PS}/f_{PS})/drewcOS_0.02"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "rew", masses[3], name)

# ######################## loops
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "f_{PS}d(M_{PS}/f_{PS})/dmul_correction"
res <- get_full_res(name, all_obs, mt) / 2
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "loop", masses[1],name)
name <- "f_{PS}d(M_{PS}/f_{PS})/dmus_correction"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "loop", masses[2],name)
name <- "f_{PS}d(M_{PS}/f_{PS})/dmuc_correction"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), "loop", masses[3],name)


## plot
gg <- ggplot() +
  theme_bw() # myggplot(fill = FALSE)
gg <- gg + geom_pointrange(
  data = df,
  aes(x = 1 / mass+10*runif(length(mass)), y = dm, ymin = dm - ddm, ymax = dm + ddm, color = label, shape = label)
)
gg <- gg + theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))

fig <- myplotly(gg, "", "$1/am$", "$f_{PS}d(M_{PS}/f_{PS})/d\\mu$",
  to_print = TRUE,
  # legend_position = "right"
)
###
gg <- ggplot() +
  theme_bw() # myggplot(fill = FALSE)
gg <- gg + geom_pointrange(
  data = df,
  aes(x = 1 / mass +10*runif(length(mass)) , y = dm, ymin = dm - ddm, ymax = dm + ddm, color = name, shape = name)
)
gg <- gg + theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 1))

fig <- myplotly(gg, "", "$1/am$", "$f_{PS}d(M_{PS}/f_{PS})/d\\mu$",
  to_print = TRUE,
  # legend_position = "right"
)
```

## der correlator

```{r, results='asis',echo=FALSE}
df <- data.frame(
  "dm" = c(0),
  "ddm" = c(0),
  "label" = c("")
)
df <- df[-1, ]
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "dC(t=20)/drewlTM"
res <- get_full_res(name, all_obs, mt) / 2
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0("   ", name))
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_strange_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "dC(t=20)/drewsOS"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0("  ", name))

# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.25_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
name <- "dC(t=20)/drewcOS_0.25"
res <- get_full_res(name, all_obs, mt)
df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0(" ", name))

# # ######################## rew
# mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_OS_B64.dat_output")
# all_obs <- Rose::get_all_corr(mt)
# name<-"dM_{PS}/drewcOS"
# res <- get_full_res(name, all_obs, mt)
# df[nrow(df) + 1, ] <- list(as.numeric(res[1, 1]), as.numeric(res[1, 2]), paste0(" ",name))


## plot
gg <- myggplot(fill = FALSE)
gg <- gg + geom_pointrange(
  data = df,
  aes(x = label, y = dm, ymin = dm - ddm, ymax = dm + ddm, color = label, shape = label)
)

fig <- myplotly(gg, "", "", "$dC(t=20)/d\\mu$", to_print = TRUE)
```

## mpcac sea corrections

```{r, results='asis',echo=FALSE}
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- NULL
df <- add_corr_to_df("mpcac", all_obs, mt, df, print_res = FALSE, reshape = T)
df <- add_corr_to_df("mpcac+mul_correction", all_obs, mt, df, print_res = FALSE, reshape = T, nudge = 0.1)
df <- add_corr_to_df("mpcac+mus_correction", all_obs, mt, df, print_res = FALSE, reshape = T, nudge = 0.2)
df <- add_corr_to_df("mpcac+muc_correction", all_obs, mt, df, print_res = FALSE, reshape = T, nudge = 0.3)
# df <- add_corr_to_df("W+all_mu_correction(t)", all_obs, mt, df, print_res = FALSE, reshape = FALSE)

print_full_res("mpcac", all_obs, mt)
print_full_res("mpcac+mul_correction", all_obs, mt)
print_full_res("mpcac+mus_correction", all_obs, mt)
print_full_res("mpcac+muc_correction", all_obs, mt)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("mpcac_rewlTM", all_obs, mt, df, print_res = FALSE, nudge = 0.6, reshape = T)
# print_full_res("w0_rewlTM", all_obs, mt)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_strange_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("mpcac_rewsOS", all_obs, mt, df, print_res = FALSE, nudge = 0.5, reshape = T)
# print_full_res("w0_rewsOS", all_obs, mt)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("mpcac_rewcOS", all_obs, mt, df, print_res = FALSE, nudge = 0.4, reshape = T)
# print_full_res("w0_rewcOS", all_obs, mt)


######################## rew
# this was wrong  just for checking the difference
# mt <- read_df("/home/garofalo/analysis/flow/data/out/flow_B64.dat_reweight_charm_OS_2_B64.dat_output")
# all_obs <- Rose::get_all_corr(mt)
# df <- add_corr_to_df("W_rewcOS(t)", all_obs, mt, df, print_res = FALSE, nudge = 0.1, reshape = FALSE,rename = "W2")
# print_full_res("w0_rewcOS", all_obs, mt)

#########################
# l <- which(df$x == 150 & df$label == "W(t)")
# save_res <- df[l, ]
# df <- df[seq(1, length(df$x), by = 3), ]
# print_full_res("w0+all_mu_correction", all_obs, mt)

gg <- plot_df_corr_ggplot(df, width = 0.05)
# gg<-myggplot()
# gg <- gg + geom_hline(yintercept = 0.3)

fig <- myplotly(gg, "", "$t/a$", "$m_{pcac}(t)$", to_print = TRUE)
```

# sources scaling

```{r, results='asis',echo=FALSE}
df <- NULL
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewlTM", all_obs, mt, df,
  print_res = FALSE, nudge = 0.0, reshape = T,
  rename = "M_{PS}_rewlTM_100s"
)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64_50s.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewlTM_50s", all_obs, mt, df, print_res = FALSE, nudge = 0.2, reshape = T)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64_25s.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewlTM_25s", all_obs, mt, df, print_res = FALSE, nudge = 0.4, reshape = T)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64_1s.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewlTM_1s", all_obs, mt, df, print_res = FALSE, nudge = 0.6, reshape = T)

###### plot
gg <- plot_df_corr_ggplot(df, width = 0.05, noribbon = TRUE)

fig <- myplotly(gg, "", "$t/a$", "$m_{eff}(t)$", to_print = TRUE)
```

```{r, results='asis',echo=FALSE}
df <- NULL
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_charm_0.1_OS_B64_LMA.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewcOS_0.1", all_obs, mt, df,
  print_res = FALSE, nudge = 0.0, reshape = T,
  rename = "M_{PS}_rewcOS_0.1_h20"
)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_charm_0.1_h10_OS_B64_LMA.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewcOS_0.1", all_obs, mt, df,
  print_res = FALSE, nudge = 0.1, reshape = T,
  rename = "M_{PS}_rewcOS_0.1_h10"
)
# ######################## rew
mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_charm_0.1_h5_OS_B64_LMA.dat_output")
all_obs <- Rose::get_all_corr(mt)
df <- add_corr_to_df("M_{PS}_rewcOS_0.1", all_obs, mt, df,
  print_res = FALSE, nudge = 0.2, reshape = T,
  rename = "M_{PS}_rewcOS_0.1_h5"
)

###### plot
gg <- plot_df_corr_ggplot(df, width = 0.05, noribbon = TRUE)

fig <- myplotly(gg, "", "$t/a$", "$m_{eff}(t)$", to_print = TRUE)
```

## rew history

the step in strange is dmu=-5.942533e-4 while in all the other is set to 0.1 the step for the charm dmu=2.35147398e-4

```{r, results='asis',echo=FALSE}
gg <-ggplot()+theme_bw()# myggplot(fill = FALSE,shape = FALSE)

df <- read.table("/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_charm_0.1_OS_B64_LMA.dat_history.txt",header = TRUE)
gg <- gg + geom_line(aes(x = !!seq_along(df[, 1]), y = !!(df[,3]) , color = "c h20"))
df <- read.table("/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_charm_0.1_h10_OS_B64_LMA.dat_history.txt",header = TRUE)
gg <- gg + geom_line(aes(x = !!seq_along(df[, 1]), y = !!(df[,3]) , color = "c h10"))
df <- read.table("/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_charm_0.1_h5_OS_B64_LMA.dat_history.txt",header = TRUE)
gg <- gg + geom_line(aes(x = !!seq_along(df[, 1]), y = !!(df[,3]) , color = "c h5"))
df <- read.table("/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_strange_OS_B64_LMA.dat_history.txt",header = TRUE)
gg <- gg + geom_line(aes(x = !!seq_along(df[, 1]), y = !!(df[,3]) , color = "s "))
df <- read.table("/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_step_0.01_to_0.01027408_OS_B64_LMA.dat_history.txt",header = TRUE)
gg <- gg + geom_line(aes(x = !!seq_along(df[, 1]), y = !!(df[,3]) , color = "0.01-0.01027 "))



# df <- read.table("/home/garofalo/analysis/flow/data/rewU_s_mdmu_h5_C80.txt")
# gg <- gg + geom_line(aes(x = !!seq_along(df[, 1]), y = !!(df[,6]) , color = "s-dmu h5"))
# df <- read.table("/home/garofalo/analysis/flow/data/rewU_s_pdmu_C80.txt")
# gg <- gg + geom_line(aes(x = !!seq_along(df[, 1]), y = !!(df[,6]) , color = "s+dmu"))
# df <- read.table("/home/garofalo/analysis/flow/data/rewU_s_C80.txt")
# gg <- gg + geom_line(aes(x = !!seq_along(df[, 1]), y = !!(df[,6]) , color = "s"))
# df <- read.table("/home/garofalo/analysis/flow/data/rewU_c_0.1_C80.txt")
# gg <- gg + geom_line(aes(x = !!seq_along(df[, 1]), y = !!(df[,6]) , color = "c"))


fig <- myplotly(gg, "", "conf", "$e^{w(U)-<w>}$", to_print = TRUE)
```

<!-- ```{r, results='asis',echo=FALSE} -->

<!-- gg <- ggplot() -->

<!-- dfU <- read.table("/home/garofalo/analysis/flow/data/all_rewU_c_0.25") -->

<!-- gg <- gg + geom_line(aes(x = !!seq_along(dfU[, 1]), y = !!dfU[, 6], color = "charm_0.25")) -->

<!-- dfU <- read.table("/home/garofalo/analysis/flow/data/all_rewU_c") -->

<!-- gg <- gg + geom_line(aes(x = !!seq_along(dfU[, 1]), y = !!dfU[, 6], color = "charm")) -->

<!-- fig <- myplotly(gg, "", "conf ", "$e^{w(U)-<w>}$", to_print = TRUE) -->

<!-- ``` -->

## histogram jackknife distribution

The error is the width of the distribution multiplied by $\sqrt{N-1}$

```{r, results='asis',echo=FALSE}
# kable(save_res[, c(2, 3, 7)], digits = 8)

name <- "M_{PS}"
W <- read.table(paste0("/home/garofalo/analysis/flow/data/out/", name, "_jack.txt"))
W <- W[c(-1, -length(W)), ]

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 7,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_light_TM_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
gg
```

## histogram loop

```{r, results='asis',echo=FALSE}
# kable(save_res[, c(2, 3, 7)], digits = 8)

name <- "M_{PS}+mul_correction"
W <- read.table(paste0("/home/garofalo/analysis/flow/data/out/", name, "_jack.txt"))
W <- W[c(-1, -length(W[,1])), ] # the first is the number of jacks, the last is the average

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 7,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
gg
```

```{r, results='asis',echo=FALSE}
# kable(save_res[, c(2, 3, 7)], digits = 8)

name <- "M_{PS}+mus_correction"
W <- read.table(paste0("/home/garofalo/analysis/flow/data/out/", name, "_jack.txt"))
W <- W[c(-1, -length(W)), ]

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 7,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
gg
```

```{r, results='asis',echo=FALSE}
# kable(save_res[, c(2, 3, 7)], digits = 8)

name <- "M_{PS}+muc_correction"
W <- read.table(paste0("/home/garofalo/analysis/flow/data/out/", name, "_jack.txt"))
W <- W[c(-1, -length(W)), ]

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 7,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
gg
```

## histogram rew

```{r, results='asis',echo=FALSE}
name <- "df_{PS}/drewcOS_0.1"
file<-"/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_charm_0.1_OS_B64_LMA.dat"
W <- read.table(paste0(file,"_df_{PS}_dmu_jack.txt"))

W <- W[c(-1, -length(W)), ]

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 10,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df(paste0(file,"_output"))
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
gg
```

```{r, results='asis',echo=FALSE}
name <- "df_{PS}/drewsOS"
file<-"/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_strange_OS_B64_LMA.dat"
W <- read.table(paste0(file,"_df_{PS}_dmu_jack.txt"))

W <- W[c(-1, -length(W)), ]

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 10,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df(paste0(file,"_output"))
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
gg
```

```{r, results='asis',echo=FALSE}
name <- "df_{PS}/drew_0.1232229005_to_0.1234969805_OS"
file<-"/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_step_0.1232229005_to_0.1234969805_OS_B64_LMA.dat"
W <- read.table(paste0(file,"_df_{PS}_dmu_jack.txt"))

W <- W[c(-1, -length(W)), ]

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 10,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df(paste0(file,"_output"))
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
gg
```

```{r, results='asis',echo=FALSE}
name <- "df_{PS}/drew_0.03125_to_0.03152408_OS"
file<-"/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_step_0.03125_to_0.03152408_OS_B64_LMA.dat"
W <- read.table(paste0(file,"_df_{PS}_dmu_jack.txt"))

W <- W[c(-1, -length(W)), ]

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 10,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df(paste0(file,"_output"))
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
gg
```

```{r, results='asis',echo=FALSE}
name <- "df_{PS}/drew_0.01_to_0.01027408_OS"
file<-"/home/garofalo/analysis/flow/data/out/onlinemeas_B64_LMA.dat_reweight_step_0.01_to_0.01027408_OS_B64_LMA.dat"
W <- read.table(paste0(file,"_df_{PS}_dmu_jack.txt"))

W <- W[c(-1, -length(W)), ]

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 10,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df(paste0(file,"_output"))
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
gg
```

### M

```{r, results='asis',echo=FALSE}
# kable(save_res[, c(2, 3, 7)], digits = 8)

name <- "M_{PS}_rewcOS"
W <- read.table(paste0("/home/garofalo/analysis/flow/data/out/", name, "_jack.txt"))
W <- W[c(-1, -length(W)), ]

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 10,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
### loop
#
# name<- "M_{PS}+muc_correction"
# W1 <- read.table(paste0("/home/garofalo/analysis/flow/data/out/",name,"_jack.txt"))
# W1 <- W1[c(-1, -length(W1)), ]
#
# gg <- gg +
#   geom_histogram(aes(x = W1, y = after_stat(density), colour=!!name),
#     binwidth = -(min(W1) - max(W1)) / 7,
#     # breaks = seq(min(W), max(W), by = 100),
#     fill = "white"  ) +
#   theme_bw()
#
# mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_output")
# all_obs <- Rose::get_all_corr(mt)
# fit<-get_full_res(name, all_obs, mt)
# gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1,1], sd = (fit[1,2]) / sqrt(length(W) - 1), mapping=aes(colour=!!name)))

gg + theme(legend.position = "inside")
```

```{r, results='asis',echo=FALSE}
# kable(save_res[, c(2, 3, 7)], digits = 8)

name <- "M_{PS}_rewcOS_0.25"
W <- read.table(paste0("/home/garofalo/analysis/flow/data/out/", name, "_jack.txt"))
W <- W[c(-1, -length(W)), ]

gg <- ggplot() +
  xlab(name) +
  geom_histogram(aes(x = W, y = after_stat(density)),
    binwidth = -(min(W) - max(W)) / 10,
    # breaks = seq(min(W), max(W), by = 100),
    colour = "black",
    fill = "white"
  ) +
  theme_bw()

mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_charm_0.25_OS_B64.dat_output")
all_obs <- Rose::get_all_corr(mt)
fit <- get_full_res(name, all_obs, mt)
gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))

gg + theme(legend.position = "inside")
```

```{r, results='asis',echo=FALSE}
# kable(save_res[, c(2, 3, 7)], digits = 8)
# 
# name <- "M_{PS}_rew_scndgTM"
# W <- read.table(paste0("/home/garofalo/analysis/flow/data/out/", name, "_jack.txt"))
# W <- W[c(-1, -length(W)), ]
# 
# gg <- ggplot() +
#   xlab(name) +
#   geom_histogram(aes(x = W, y = after_stat(density)),
#     binwidth = -(min(W) - max(W)) / 10,
#     # breaks = seq(min(W), max(W), by = 100),
#     colour = "black",
#     fill = "white"
#   ) +
#   theme_bw()
# 
# mt <- read_df("/home/garofalo/analysis/flow/data/out/onlinemeas_B64.dat_reweight_sc_ndg_TM_B64.dat_output")
# all_obs <- Rose::get_all_corr(mt)
# fit <- get_full_res(name, all_obs, mt)
# gg <- gg + stat_function(fun = dnorm, args = list(mean = fit[1, 1], sd = (fit[1, 2]) / sqrt(length(W) - 1)))
# 
# gg + theme(legend.position = "inside")
```
