# quark masses


```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)


df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x, y)) +
    geom_point()
  assign("ggp", plotly::ggplotly(gg), envir = parent.frame())
  # ggp
  df # NOT returning a plot
}
res1 <- f1(df)
ggp # Let knit handle the plot
myplotly(ggplot())
masses <- c(
  0.0006669,
  0.018267,
  0.23134
)
from_21_to_4 <- 0.826399813665257
from_21_to_9 <- 0.91708855448905
```


$$
m(f) = c_0(f) \left[1+c_1(f,Z) a^2 + c_l(Z)a^2\log (a^2\Lambda^2)\right]
$$

```{r,results='asis',echo=FALSE, warning=FALSE}
gg <- NULL
basenames <- c(
  "/home/garofalo/analysis/flow/data/fit_all_beta/fit_masses_from_fpi_cont_a2",
  "/home/garofalo/analysis/flow/data/fit_all_beta/fit_mass_light_from_fpi_cont_a2"
)
labels <- c(
  "FLAG-scheme",
  "ml-only"
)


for (j in seq_along(basenames)) {
  print(basenames[j])
  fit <- Rose::read_fit_P_file(paste0(basenames[j], "_fit_P.dat"))
  ml_4GeV <- fit$P[1, 2] / from_21_to_4
  dml_4GeV <- fit$P[1, 3] / from_21_to_4
  cat("ml(4GeV) = ", mean_print(ml_4GeV, dml_4GeV), "\n")
  if (j != 2) {
    ms_4GeV <- fit$P[2, 2] / from_21_to_4
    dms_4GeV <- fit$P[2, 3] / from_21_to_4
    cat("ms(4GeV) = ", mean_print(ms_4GeV, dms_4GeV), "\n")
    mc_4GeV <- fit$P[3, 2] / from_21_to_4
    dmc_4GeV <- fit$P[3, 3] / from_21_to_4
    cat("mc(9GeV) = ", mean_print(mc_4GeV, dmc_4GeV), "\n")
  }

  print(make_table_fit_result(fit))
  # print(tab)
  gg <- plot_fit(basenames[j], "a2",
    # noline = TRUE,
    data_type = c("ml", "ml", "ms", "ms", "mc", "mc"),
    gg = gg,
    id_x = 1,
    single_name_for_fit = labels[j],
    width = 0.0001
  )
}

fig <- myplotly(gg, "", "$a^2 [\\mbox{fm}^2]$", "$m(f,21 \\mbox{GeV}) [\\mbox{MeV}]$",
  to_print = TRUE,
  # yrange = c(-1, 4),
  legend_position = c(0.7, 0.98)
)
```
