# system scale setting


```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)


df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x, y)) +
    geom_point()
  assign("ggp", plotly::ggplotly(gg), envir = parent.frame())
  # ggp
  df # NOT returning a plot
}
res1 <- f1(df)
ggp # Let knit handle the plot
myplotly(ggplot())
masses <- c(
  0.0006669,
  0.018267,
  0.23134
)
```

```{r,results='asis',echo=FALSE, warning=FALSE}
df <- read.table("/home/garofalo/analysis/flow/data/fit_all_beta/data_from_fpi.txt", header = TRUE)
start_indices <- seq(2, ncol(df), by = 2)
new_df <- data.frame(df[,c(1,start_indices)])
colnames(new_df) <- colnames(df)[c(1,start_indices)]
new_df[,1]<- df[,1]
for( i in seq_along(start_indices)){
  for (row in seq_along(df[,1])){
    new_df[row,i+1] <-mean_print(df[row,start_indices[i]], df[row,start_indices[i]+1])
  }
}
kable(new_df)

# kable(df)
df <- read.table("/home/garofalo/analysis/flow/data/fit_all_beta/data_from_w0.txt", header = TRUE)
start_indices <- seq(2, ncol(df), by = 2)
new_df <- data.frame(df[,c(1,start_indices)])
colnames(new_df) <- colnames(df)[c(1,start_indices)]
new_df[,1]<- df[,1]
for( i in seq_along(start_indices)){
  for (row in seq_along(df[,1])){
    new_df[row,i+1] <-mean_print(df[row,start_indices[i]], df[row,start_indices[i]+1])
  }
}
kable(new_df)

```


```{r,results='asis',echo=FALSE, warning=FALSE}
gg <- NULL
basenames <- c(
  "/home/garofalo/analysis/flow/data/fit_all_beta/fit_w0_cont_a2",
  "/home/garofalo/analysis/flow/data/fit_all_beta_no_charm_sea_w0/fit_w0_cont_a2",
  "/home/garofalo/analysis/flow/data/fit_all_beta_nocorw0/fit_w0_cont_a2"
)
labels <- c(
  "P[0]+ P[1]*a2 ",
  "-no-charm-sea-w0",
  "sim-point"
)


for (j in seq_along(basenames)) {
  print(basenames[j])
  fit <- Rose::read_fit_P_file(paste0(basenames[j], "_fit_P.dat"))
  make_table_fit_result(fit)
  gg <- plot_fit(basenames[j], "a2",
    # noline = TRUE,
    data_type = c(labels[j]),
    gg = gg,
    id_x = 1,
    single_name_for_fit = labels[j],
    width = 0.0001
  )
}
w0_wp25 <- 0.17236
gg <- gg + geom_hline(yintercept = w0_wp25, linetype = "dashed")
gg <- gg + geom_point(aes(x = 0, y = w0_wp25, color = "wp25", shape = "wp25", fill = "wp25"))

fig <- myplotly(gg, "", "$a^2 [\\mbox{fm}^2]$", "$w_0 [\\mbox{fm}]$",
  to_print = TRUE,
  # yrange = c(-1, 4),
  legend_position = c(0.7, 0.98)
)
```



```{r,results='asis',echo=FALSE, warning=FALSE}
gg <- NULL
basenames <- c(
  "/home/garofalo/analysis/flow/data/fit_all_beta/fit_fpi_cont_a2"
)
labels <- c(
  "P[0]+ P[1]*a2 "
)


for (j in seq_along(basenames)) {
  print(basenames[j])
  fit <- Rose::read_fit_P_file(paste0(basenames[j], "_fit_P.dat"))
  make_table_fit_result(fit)
  gg <- plot_fit(basenames[j], "a2",
    # noline = TRUE,
    data_type = c("data"),
    gg = gg,
    id_x = 1,
    single_name_for_fit = labels[j],
    width = 0.0001
  )
}
fpi_FLAG <- 130.5
gg <- gg + geom_hline(yintercept = fpi_FLAG, linetype = "dashed") #+annotate("text", x = 0.0002, y = fpi_FLAG-0.2, label="FLAG")
gg <- gg + geom_point(aes(x = 0, y = fpi_FLAG, color = "FLAG", shape = "FLAG", fill = "FLAG"))

fig <- myplotly(gg, "", "$a^2 [\\mbox{fm}^2]$", "$f_{\\pi} [\\mbox{MeV}]$",
  to_print = TRUE,
  # yrange = c(-1, 4),
  legend_position = c(0.7, 0.98)
)
```




```{r,results='asis',echo=FALSE, warning=FALSE}
gg <- NULL
basenames <- c(
  "/home/garofalo/analysis/flow/data/fit_all_beta/fit_ms_over_ml_from_fpi_cont_a2",
  "/home/garofalo/analysis/flow/data/fit_all_beta/fit_ms_over_ml_from_w0_cont_a2"
)
labels <- c(
  "FLAG",
  "wp25"
)


for (j in seq_along(basenames)) {
  print(basenames[j])
  fit <- Rose::read_fit_P_file(paste0(basenames[j], "_fit_P.dat"))
  make_table_fit_result(fit)
  gg <- plot_fit(basenames[j], "a2",
    # noline = TRUE,
    data_type = c(labels[j]),
    gg = gg,
    id_x = 1,
    single_name_for_fit = labels[j],
    width = 0.0001
  )
}

# Creazione del dataframe con valore centrale ed errore
df <- data.frame(
  x = 0,
  y = 27.227,
  incertezza = 0.081,
  lab = "FLAG24"
)

gg <- gg + geom_point(data = df, aes(x = x, y = y, color = lab, shape = lab, fill = lab)) +
  # Barra di errore (y +/- incertezza)
  geom_errorbar(
    data = df, aes(
      x = x,
      y = y,
      ymin = y - incertezza,
      ymax = y + incertezza, color = lab, shape = lab, fill = lab
    ),
    width = 0.0001
  )

fig <- myplotly(gg, "", "$a^2 [\\mbox{fm}^2]$", "$m_s/m_\\ell$",
  to_print = TRUE,
  # yrange = c(-1, 4),
  legend_position = c(0.7, 0.98)
)
```


```{r,results='asis',echo=FALSE, warning=FALSE}
gg <- NULL
basenames <- c(
  "/home/garofalo/analysis/flow/data/fit_all_beta/fit_mc_over_ms_from_fpi_cont_a2",
  "/home/garofalo/analysis/flow/data/fit_all_beta/fit_mc_over_ms_from_w0_cont_a2",
  "/home/garofalo/analysis/flow/data/fit_all_beta_no_charm_sea_w0//fit_mc_over_ms_from_w0_cont_a2"
)
labels <- c(
  "FLAG",
  "wp25",
  "wp25-no-charm-sea-w0"
)


for (j in seq_along(basenames)) {
  print(basenames[j])
  fit <- Rose::read_fit_P_file(paste0(basenames[j], "_fit_P.dat"))
  make_table_fit_result(fit)
  gg <- plot_fit(basenames[j], "a2",
    # noline = TRUE,
    data_type = c(labels[j]),
    gg = gg,
    id_x = 1,
    single_name_for_fit = labels[j],
    width = 0.0001
  )
}
# Creazione del dataframe con valore centrale ed errore
df <- data.frame(
  x = 0,
  y = 11.766,
  incertezza = 0.030,
  lab = "FLAG24"
)

gg <- gg + geom_point(data = df, aes(x = x, y = y, color = lab, shape = lab, fill = lab)) +
  # Barra di errore (y +/- incertezza)
  geom_errorbar(
    data = df, aes(
      x = x,
      y = y,
      ymin = y - incertezza,
      ymax = y + incertezza, color = lab, shape = lab, fill = lab
    ),
    width = 0.0001
  )

fig <- myplotly(gg, "", "$a^2 [\\mbox{fm}^2]$", "$m_c/m_s$",
  to_print = TRUE,
  # yrange = c(-1, 4),
  legend_position = c(0.7, 0.98)
)
```


```{r,results='asis',echo=FALSE, warning=FALSE}
gg <- NULL
basenames <- c(
  "/home/garofalo/analysis/flow/data/fit_all_beta/fit_afpi_over_aw0_cont_a2"
)
labels <- c(
  "P[0]+P[1]a2"
)


for (j in seq_along(basenames)) {
  print(basenames[j])
  fit <- Rose::read_fit_P_file(paste0(basenames[j], "_fit_P.dat"))
  make_table_fit_result(fit)
  gg <- plot_fit(basenames[j], "a2",
    # noline = TRUE,
    data_type = c(labels[j]),
    gg = gg,
    id_x = 1,
    single_name_for_fit = labels[j],
    width = 0.0001
  )
}

fig <- myplotly(gg, "", "$a^2_{FLAG} [\\mbox{fm}^2]$", "$a_{FLAG}/a_{wp25}$",
  to_print = TRUE,
  # yrange = c(-1, 4),
  legend_position = c(0.7, 0.98)
)
```


```{r,results='asis',echo=FALSE, warning=FALSE}
gg <- NULL
basenames <- c(
  "/home/garofalo/analysis/flow/data/fit_all_beta/fit_afpi_minus_aw0_cont_a2",
  "/home/garofalo/analysis/flow/data/fit_all_beta_no_charm_sea_w0//fit_afpi_minus_aw0_cont_a2"
)
labels <- c(
  "P[0]+P[1]a2",
  "wp25-no-charm-sea-w0"
)


for (j in seq_along(basenames)) {
  print(basenames[j])
  fit <- Rose::read_fit_P_file(paste0(basenames[j], "_fit_P.dat"))
  make_table_fit_result(fit)
  gg <- plot_fit(basenames[j], "a2",
    # noline = TRUE,
    data_type = c(labels[j]),
    gg = gg,
    id_x = 1,
    single_name_for_fit = labels[j],
    width = 0.0001
  )
}

fig <- myplotly(gg, "", "$a^2_{FLAG} [\\mbox{fm}^2]$", "$a_{FLAG}-a_{wp25}$",
  to_print = TRUE,
  # yrange = c(-1, 4),
  legend_position = c(0.7, 0.98)
)
```
